---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Generates a pull request on demand
name: 'Generate Pull Request ⬇️'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '40 6 * * 0'

permissions: {}

jobs:
  generate-pr:
    name: 'Generate Pull Request ⬇️'
    runs-on: 'ubuntu-24.04'
    permissions:
      # Needed to add/update a file in the repository
      contents: write
      # Needed to raise the pull request
      pull-requests: write
      # Needed to create pull request labels
      issues: write

    timeout-minutes: 5
    steps:
      - name: 'Harden runner 🔒'
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - name: 'Checkout local repository ☑️'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: 'List existing pull requests 📋'
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          # List pull requests with label/search
          requests=$(gh pr list -l 'automated pr')
          if [ -n "$requests" ]; then
            echo 'Pull requests 💬'
            echo "$requests"
          fi

      - name: "Running local action: ${{ github.repository }} 🔨"
        uses: ./
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
